interface User {
    id : number,
    name : string,
    role : string,
    address : string,
    salary : number,
};
export const users : User[] = [
    {
      id: 1,
      name: 'Jorge',
      role: 'Developer',
      address: '358',
      salary: 150,
    },
    {
      id: 2,
      name: 'Jose',
      role: 'Manager',
      address: '582',
      salary: 200,
    },
    {
      id: 3,
      name: 'Pedro',
      role: 'Marketing',
      address: '638',
      salary: 120,
    },
    {
      id: 4,
      name: 'MinGyo',
      role: 'Marketing',
      address: '358',
      salary: 200,
    },
    {
      id: 5,
      name: 'Horse',
      role: 'HR',
      address: '420',
      salary: 20,
    },
    {
      id: 6,
      name: 'Alice',
      role: 'Developer',
      address: '123',
      salary: 180,
    },
    {
      id: 7,
      name: 'Bob',
      role: 'Manager',
      address: '456',
      salary: 220,
    },
    {
      id: 8,
      name: 'Emma',
      role: 'Marketing',
      address: '789',
      salary: 130,
    },
    {
      id: 9,
      name: 'John',
      role: 'Marketing',
      address: '987',
      salary: 190,
    },
    {
      id: 10,
      name: 'Sara',
      role: 'HR',
      address: '654',
      salary: 30,
    },
    {
      id: 11,
      name: 'Michael',
      role: 'Developer',
      address: '321',
      salary: 170,
    },
    {
      id: 12,
      name: 'Laura',
      role: 'Manager',
      address: '654',
      salary: 210,
    },
    {
      id: 13,
      name: 'David',
      role: 'Marketing',
      address: '987',
      salary: 140,
    },
    {
      id: 14,
      name: 'Sophia',
      role: 'Marketing',
      address: '789',
      salary: 160,
    },
    {
      id: 15,
      name: 'Ryan',
      role: 'HR',
      address: '123',
      salary: 40,
    },
  ];
  
